=== pboymt/ddns-at-home/settings.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "家庭公网IP用DDNS服务",
    "additionalProperties": false,
    "required": [
        "$schema",
        "version",
        "global",
        "services"
    ],
    "properties": {
        "$schema": {
            "type": "string",
            "description": "The schema to verify this document against.",
            "default": "./settings.v2.schema.json"
        },
        "version": {
            "type": "number",
            "title": "配置文件版本",
            "description": "当配置文件版本为1时，不存在此字段",
            "const": 2,
            "default": 2
        },
        "global": {
            "type": "object",
            "description": "部分全局设置",
            "required": [
                "disableIPv6",
                "disableIPv4",
                "TTL"
            ],
            "properties": {
                "disableIPv6": {
                    "type": "boolean",
                    "description": "禁用IPv6设置（不设置AAAA记录）",
                    "default": false
                },
                "disableIPv4": {
                    "type": "boolean",
                    "description": "禁用IPv4设置（不设置A记录）",
                    "default": false
                },
                "TTL": {
                    "type": "number",
                    "description": "域名记录TTL值",
                    "default": 600
                }
            }
        },
        "services": {
            "type": "array",
            "description": "使用的域名服务配置",
            "minItems": 1,
            "items": [
                {
                    "type": "object",
                    "title": "阿里云配置",
                    "additionalProperties": false,
                    "required": [
                        "name",
                        "apiKey",
                        "apiSecret",
                        "domains"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "title": "服务名称",
                            "description": "这是Aliyun的配置",
                            "const": "aliyun",
                            "default": "aliyun"
                        },
                        "apiKey": {
                            "type": "string",
                            "title": "具有Domain和DNS权限的API Key"
                        },
                        "apiSecret": {
                            "type": "string",
                            "title": "具有Domain和DNS权限的API Secret"
                        },
                        "domains": {
                            "type": "array",
                            "title": "域名列表",
                            "minItems": 1,
                            "items": {
                                "type": "object",
                                "title": "DDNS域名设置",
                                "additionalProperties": false,
                                "required": [
                                    "domainName",
                                    "resourceRecords"
                                ],
                                "properties": {
                                    "domainName": {
                                        "type": "string",
                                        "title": "域名"
                                    },
                                    "resourceRecords": {
                                        "type": "array",
                                        "title": "域名记录列表",
                                        "minItems": 1,
                                        "items": {
                                            "type": "object",
                                            "additionalProperties": false,
                                            "required": [
                                                "resourceRecord"
                                            ],
                                            "properties": {
                                                "resourceRecord": {
                                                    "type": "string",
                                                    "title": "域名记录"
                                                },
                                                "disableIPv6": {
                                                    "type": "boolean",
                                                    "title": "禁用IPv6设置（不设置AAAA记录）",
                                                    "default": false
                                                },
                                                "disableIPv4": {
                                                    "type": "boolean",
                                                    "title": "禁用IPv4设置（不设置A记录）",
                                                    "default": false
                                                },
                                                "TTL": {
                                                    "type": "number",
                                                    "title": "域名记录TTL值",
                                                    "description": "请谨慎使用小于600的值",
                                                    "default": 600,
                                                    "minimum": 1
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        },
        "schedule": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "immediate"
            ],
            "properties": {
                "immediate": {
                    "type": "boolean",
                    "default": true
                },
                "hour": {
                    "type": "string",
                    "default": "*",
                    "pattern": "^(\\*|2[0-3]|1[0-9]|[0-9]|\/[2-9]|\/1[0-2])$"
                },
                "minute": {
                    "type": "string",
                    "default": "/5",
                    "pattern": "^(\\*|[0-9]|[1-5][0-9]|\/[2-9]|\/[1-5][0-9])$"
                }
            }
        }
    }
}

=== pboymt/ddns-at-home/settings.sample.json
{
    "$schema": "./settings.schema.json",
    "version": 2,
    "global": {
        "disableIPv4": false,
        "disableIPv6": false,
        "TTL": 600
    },
    "services": [
        {
            "name": "aliyun",
            "apiKey": "<aliyun api key>",
            "apiSecret": "<aliyun api secret>",
            "domains": [
                {
                    "domainName": "example.com",
                    "resourceRecords": [
                        {
                            "resourceRecord": "home",
                            "disableIPv4": false,
                            "disableIPv6": true,
                            "TTL": 600
                        }
                    ]
                }
            ]
        }
    ],
    "schedule": {
        "immediate": false
    }
}
